name: 'Continuous Integration'

env:
  SERVICE_NAME: latam-challenge
  PROJECT_ID: latam-challenge-436723

on:
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Evaluate API tests
        uses: make api-test